# Structure of Function

In [2]:
# define function
def welcome_message():
  print("hello World!")

In [3]:
welcome_message()

hello World!

In [4]:
def welcome_message(user):
  print(f"hello {user}")

welcome_message("Phitron")

hello Phitron

In [13]:
def welcome_user(user="none"):
  print(f"hello {user}")

welcome_user("Phitron")
welcome_user()

hello Phitron
hello none

In [15]:
def adder (a,b):
  """
  metadata of funtion
  add two numbers

  a --> int
  b --> int
  """

  sum = a+b
  return sum

m = adder(10,30) * 5
print(m)

200

In [16]:
help(adder)

Help on function adder in module __main__:

adder(a, b)
    metadata of funtion
    add two numbers

    a --> int
    b --> int

In [17]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

### Different types of arguement

In [19]:
def adder(a,b,c):
  print(f"{a}, {b}, {c}")
adder(10,20,30)

10, 20, 30

In [22]:
def adder(*args):
  for i in args:
    print(i)

adder(10,20,30,40,50)

10
20
30
40
50

In [24]:
def adder(a=10,b=30,c=10):
  print(f"{a}, {b}, {c}")

adder()
adder(15,30,60)

10, 30, 10
15, 30, 60

In [25]:
def adder(**kwargs):
  for key, value in kwargs.items():
    print(f"{key} : {value}")

adder(a=10,b=30,c=40,n_estimator=50)

a : 10
b : 30
c : 40
n_estimator : 50

### Return Type

In [26]:
def welcome_message():
  print("hello user")

print(type(welcome_message()))

hello user
<class 'NoneType'>

In [29]:
def adder(a,b):
  sum=a+b
  return sum

print(type(adder(10,20)))
print(type(adder(10.5,20)))
print(type(adder("arman","habib")))

<class 'int'>
<class 'float'>
<class 'str'>

In [30]:
def welcome_message(user="None"):
  return f"hello {user}"

print(type(welcome_message()))

<class 'str'>

### Iterator

In [41]:
s = {10,20,30,40,50}

s_iter = iter(s)
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))

for i in s:
  print(i)

50
20
40
10
30
50
20
40
10
30

### generator

In [51]:
lst = [x for x in range(500)]   # dataset

def data_loader(chunk_size, lst):
  for i in range(0, len(lst), chunk_size):
    yield lst[i:i+chunk_size]

x = data_loader(5,lst)

print(next(x))
print(next(x))

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]

### Lambda, map and apply function

In [62]:

import pandas as pd


df = pd.DataFrame({'temperature (F)': [32, 212, 98.6, 68]})
df

df['temperature (C)'] = df['temperature (F)'].apply(lambda x: (x - 32) * 5/9)
df

df["temperature(K)"] = df["temperature (F)"].apply(lambda x: ((x-32)*5/9)+273)
df

   temperature (F)  temperature (C)  temperature(K)
0             32.0              0.0           273.0
1            212.0            100.0           373.0
2             98.6             37.0           310.0
3             68.0             20.0           293.0

In [63]:
def adder(a,b):
  return [a,b]

print(type(adder(10.5,20)))

<class 'list'>

In [64]:
# unzip

x,y = adder(10.5,20)

print(x)
print(y)

10.5
20

In [66]:
import pandas as pd

df = pd.DataFrame({'A':[1,2,3,4], 'B':[5,6,7,8]})
df

df['A'] = df['A'].apply(lambda x: x**0.5)
df

          A  B
0  1.000000  5
1  1.414214  6
2  1.732051  7
3  2.000000  8

In [67]:
import pandas as pd

df = pd.DataFrame({'total_spent' : [120,600,450,800]})

# Creating a 'High Value' feature on the fly
df['is_high_value'] = df['total_spent'].apply(lambda x: 1 if x>500 else 0  )
df

   total_spent  is_high_value
0          120              0
1          600              1
2          450              0
3          800              1